### ISSUE TITLE
Add support for deletion of resources

### ISSUE THREAD

**Issue by davecap** [solvebio/solvebio-r#34]
* Depository
* Dataset

**Comment by iainmwallace** [comment]
Hi,

When using the Dataset.delete() command, the data from the dataset is deleted but the dataset itself is still present in the WebUI. Is there any way to completely remove it?

Also, how do I delete a "Vault"?

Thanks

Iain

**Comment by davecap** [comment]
Hmm, that seems like a bug on our end. I've temporarily fixed the issue so the datasets you deleted should not show up but it may happen again for future datasets.

Just to clarify, what do you mean when you say "Vault"?

**Comment by iainmwallace** [comment]
Thanks - by "Vault", I mean the private datafeeds on the UI, the folder where I am storing datasets

**Comment by davecap** [comment]
Ah ok, yes it is a bit confusing but you would use the `Depository.delete(<id>)`. If your dataset is called "domain:X/1.0.0/Z", it would be `Depository.delete("domain:X")`. In a couple of weeks we will be rolling out changes that make this must more straight forward.

**Comment by iainmwallace** [comment]
I get an error when I run the command Depository.delete() with the specific 
Error in .request("DELETE", path = path) : API error: 404

Interestingly, only one of my vaults is listed when I run the command Depository.all()

**Comment by davecap** [comment]
Try using this command to list your private Depositories:

```
Depository.all(visibility="private")
```

**Comment by davecap** [comment]
Looks like there was a typo in that code block, fixed in the master branch.

**Comment by iainmwallace** [comment]
That worked, thanks!
