### ISSUE TITLE
issue loading files into sub directory in a vault

### ISSUE THREAD

**Issue by iainmwallace** [solvebio/solvebio-r#56]
Hi,

I am having an issue loading files into a sub directory of vault. The subdirectories are getting duplicated. Is there another option/flag that I should be using to make sure the files are loaded correctly?

    library(uuid)
    my_filename<-"sample_file.csv"
    
    ## uploads file into subdirectory '/test_dir/'
    unique_filename<-paste0(UUIDgenerate(),"_",my_filename)
    file.copy(my_filename,unique_filename)
    object <- Object.upload_file(unique_filename, vault$id, '/test_dir/')
    
    ## uploads file into subdirectory '/test_dir-1/' not '/test_dir/'
    unique_filename<-paste0(UUIDgenerate(),"_",my_filename)
    file.copy(my_filename,unique_filename)
    object <- Object.upload_file(unique_filename, vault$id, '/test_dir/')

Thanks,

Iain

**Comment by davecap** [comment]
Are you using version 2.0.1? There were some changes that may have fixed this issue.

**Comment by iainmwallace** [comment]
I am using the latest version from github as of today. I just reran my sample code, and the issue was still there.

**Comment by davecap** [comment]
It looks like it was getting tripped up by the trailing slash in the vault path. I've pushed a fix to master, but it should work if you remove the trailing slash from `/test_dir/`.

**Comment by iainmwallace** [comment]
That works, thanks!

**Comment by davecap** [comment]
Great, this fix will go out in the next release.
