### ISSUE TITLE
Issue increasing facet limits

### ISSUE THREAD

**Issue by iainmwallace** [solvebio/solvebio-r#60]
Hi,

How do I increase the number of facets returned? 
The code below only returns the top 10 rather than the 100 I expected

    dataset <- Dataset.get_by_full_path("solvebio:public:/TargetValidation/1.0.1-17.04/Association")
    Dataset.facets(dataset$id,list("disease.efo_info.label"),limit=100)

Thanks

Iain

**Comment by davecap** [comment]
Good question, this one is a bit tricky and not as easy as it should be. Try this:

```
Dataset.facets(dataset$id, list("disease.efo_info.label"=list(limit=1000)))
```

The idea being that you can request multiple facets at the same time:

```
Dataset.facets(dataset$id, list("disease.efo_info.label"=list(limit=1000), "field_2"=list(limit=100)))
```

**Comment by iainmwallace** [comment]
That worked, thanks!
