### ISSUE TITLE
Add support for creating and querying Beacon Sets

### ISSUE THREAD

**Issue by davecap** [solvebio/solvebio-r#62]
New feature in v2.

**Comment by iainmwallace** [comment]
Is there documentation on how to do this with the API? The current documentation refers to v1
https://docs.solvebio.com/reference/datasets/beacons/

**Comment by davecap** [comment]
New reference documentation for beacon sets and beacons is available now: https://docs.solvebio.com/reference/beacons/endpoints/

Implementation in the R client will be available in the next couple of days.
